language: java

sudo: false

jdk: openjdk8

addons:
  sonarcloud:
    organization: "qlack"
    token:
      secure: "UMjg+xrzPKa+OCNJagTPTJGYAe4RF1r4vEML1WsHm8UBUdsFU3C9KtjmYAHmrFRZETCxvXwAv+4wiVZ7HlILPWOqGB9aWY7ma9QbJtO07q2Ptkq4LBo7D38m9m1fhse3TawyhNfKW7op6yrVjCptVld8BVFNhdGGqVVKqXluTGyXr7jcNCDM8UypuYbGirHlVHtKuC/mDerChSAP0c0cDhLgWX0i+hhCnNlyaSrzhUtJn1VS307yFaX8L4exfde/LxMh2lBUMZN7uIJFKUqqYSLjRjKvCfBtwcDGjUMJ6hAywQkg1lmsqgd0AvUBzcqXF5vlPAVcLvIhLyZXsSGW5n+OiV937uJg6Pi/NFfrJ9KKor4n/L3wXlcQcUGnzLSOiiD4C/uG45y+DAsPNvsDF2rT5T6F3eGxwwxqyXr/7qqo0yqRga3Pts+u4B93J3MWlnNHJqibWkC7UlciMOUnze1egjO2vvb16ZyAcR9HvZXcke+5cnBo9cBk8BNofmk+5tVGJLGUiYjV3WFQ43152vs6YUYnafht/sp4vnz3b/Ctk4a8WfbafOPsFYmrO33hN7mJ/f2uvyBdNfKmdvkfuyYqxWtaMQ/YSbOJMy5Xrq4WU1rmc7hFILgXqwiBPzLU4EURE2k03bZlf09vy++IFK8BVjn0Lm9zJ0SG2TiPTgg="

script: mvn clean install sonar:sonar -Dsonar.projectKey=qlack_be
