language: java

sudo: false

jdk: openjdk8

addons:
  sonarcloud:
    organization: "qlack"
    token:
      secure: "JE/QMA5Q+9+bfwdkfYE8Gpu84az7jnXL5P/h0PCKxl8BKsZObTehEtuCWaqx6+axJ4M7vUJm4TgTSUiVtMD4qXRYC7DcMlSFhZcNKa7XoJF3HYy8IF8dNzjylRjECr3IlW1Qx4HS776aGL7cJasb0EjgAD9bsOYzgFhy6xGkMlGGkjlKvW9ixQUFd0feyCZPTkmcO41ZIUrhMvrgFMA+1l3O3muiGOxNQSFpbwdXhia4VZGTAjj3vvNIm5Nq0XsINFovu2Sn0cH0hS74ThhnoqKk2jFyeXBqit8odijM6Lc1ISRak3o9lpRS/+63ARyXSJXDy1IR6M6+skEu3AHSZAYCpX0xq6HG5ZwzFToVnzbxxKGEPKPv0IYRKTWf3pFQI96bRPq3/L4WDPUhJfzkvUVGaEZjvfZtvwJtrj8A8LVhHhpZJVakvWyENr59ia8twniNbMRhrCHP1s4vP8INuVS92xT5ELgF/rwARKShITEniOn8FR2Irxm/1o1Ih9hDmKOBwC+9MFWd4axAvxC4WiicQxELKs+w8qCPV5dhqxPigNWKxfhFoPmlX8A+6HjJhximPaG4gBn+52wnv2bGGC7vYkrGq8Wy0rYGByfdv5WJxS+fMi50bXYCEOzDD2ZIgVXhyeeUQjn4D+VRUl5Hqf6V6S2yz9pNuAnsph2/7cY="

script: mvn clean install sonar:sonar -Dsonar.projectKey=qlack_be
