language: java

sudo: false

jdk: openjdk8

addons:
  sonarcloud:
    organization: "qlack"
    token:
      secure: "tje0dWiCf9suwvm428h/fOxv6uWyTZoXpMIJOVFLnS+qsxQ9AyACmWhJv2K+kf0w1RBgp/ZoV/bmyvfJG8RyrXhKe/v4MbY+mr9YalsK3uGzdsVe75Ag+oXMejzEgR9b1AE5+jrMzwmtI7B06wsa4H5y+qJctkNyCbRg5Qyi8Ug6SGQZDpKo+BQ6Y48t0h+viGavcbnGTvPngL3/LiKUjvTu0PWPt7ZkwPwW1EtTjtVBEIJXbEYlJm/OxIv1IEKGIWhkP+n79cTvVQ6iPEfRYOM+JnyzmBySytqK5iJkSFOnMp/9Ca2KFs7ZYAIfHfYqihmrChAXj91YIbxiq4eQYdQKXVkc9j98EL56NnVHW2S/mHiuoC+mhUz2MGrWuVfAR9H6gewU1f2oYR/O1hJHfUY/8Zv/5a2vyG6sFGZrlDvJgp7fGBIl0pXRm8gt5rx8ORYkNfBl9m/2HP6+0Xy/nvKROJNKeYn8zIgungPal0rnfsop/LKjPIcs6XUHwKUmCe5d0cy7cic/HqbJUvYY2Vqyz6b05OlKZpD8Wq+JigfNvgnhwpRpEK5yFT08+NB39vOpcc75gZE2+DwsEHixXBMtkhjkbjLBi3yUZLqsBu7fpZ/qqyNQ6wWHbMpbZ5333/gMNKSiYD1yWmPK0CZqK8C1/4yXlXh3Z+Q6Z/nvtj4="

script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=qlack_QLACK-BusinessEngine
